<a href="https://colab.research.google.com/github/Shikha9557/Deep-Learning-Exp/blob/main/basic_function_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# Display TensorFlow version
print("TensorFlow Version:", tf.__version__)

# Creating tensors
a = tf.constant([1, 2, 3, 4])
b = tf.constant([5, 6, 7, 8])

print("\nTensor A:")
print(a)

print("\nTensor B:")
print(b)

# Basic operations
addition = tf.add(a, b)
subtraction = tf.subtract(a, b)
multiplication = tf.multiply(a, b)

print("\nAddition:")
print(addition)

print("\nSubtraction:")
print(subtraction)

print("\nMultiplication:")
print(multiplication)

# Creating a matrix
matrix = tf.constant([
    [1, 2],
    [3, 4]
])

print("\nMatrix:")
print(matrix)

# Reshaping a tensor
x = tf.constant([1, 2, 3, 4, 5, 6])

reshaped_x = tf.reshape(x, [2, 3])

print("\nOriginal Tensor:")
print(x)

print("\nReshaped Tensor:")
print(reshaped_x)

TensorFlow Version: 2.20.0

Tensor A:
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)

Tensor B:
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)

Addition:
tf.Tensor([ 6  8 10 12], shape=(4,), dtype=int32)

Subtraction:
tf.Tensor([-4 -4 -4 -4], shape=(4,), dtype=int32)

Multiplication:
tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)

Matrix:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

Original Tensor:
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)

Reshaped Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

# Create sample input data
X = np.array([
    [0],
    [1],
    [2],
    [3],
    [4],
    [5]
], dtype=np.float32)

# Corresponding output data
Y = np.array([
    [0],
    [2],
    [4],
    [6],
    [8],
    [10]
], dtype=np.float32)

# Create a Sequential Keras model
model = keras.Sequential([
    layers.Dense(8, activation='relu', input_shape=(1,)),
    layers.Dense(1)
])
# Compile the model
model.compile(
    optimizer='adam',
    loss='mean_squared_error'
)

# Display model architecture
model.summary()

# Train the model
model.fit(X, Y, epochs=100, verbose=0)

# Make a prediction
prediction = model.predict(np.array([[10]], dtype=np.float32), verbose=0)

print("\nPrediction for input 10:")
print(prediction)



Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 8)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 25 (100.00 B)

 Trainable params: 25 (100.00 B)

 Non-trainable params: 0 (0.00 B)


Prediction for input 10:
[[3.414717]]
